name: build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x, 1.15.x, 1.16.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.version }}

    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint

    - name: build
      run: go build .

    - name: Test with coverage
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1

    - name: Run vet & lint
      run: |
        go vet .
        golint -set_exit_status=1 .