name: tests
on: [push]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x, 1.15.x, 1.16.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.version }}

    - name: Version
      run: go version

    - name: Tests
      run: go test -v -race ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1